In [2]:
import pandas as pd

# Data processing

Import data and join tables

In [31]:
# Import tables from the raw data directory
conditions = pd.read_csv('../raw_data/Conditions.txt', sep='\t')
experiment_conditions = pd.read_csv('../raw_data/ExperimentConditions.txt', sep='\t')
experiments = pd.read_csv('../raw_data/Experiments.txt', sep='\t', encoding='latin1')
logcs = pd.read_csv('../raw_data/LogCs.txt', sep='\t')
properties = pd.read_csv('../raw_data/Properties.txt', sep='\t')
response_properties = pd.read_csv('../raw_data/ResponseProperties.txt', sep='\t')
responses = pd.read_csv('../raw_data/Responses.txt', sep='\t', encoding='latin1')
source = pd.read_csv('../raw_data/Source.txt', sep='\t')

In [32]:
logcs.head()

   ID  ResponseID    Time  Value ComBaseID
0   1       38694    0.00   4.02       A_1
1   2       38694   22.50   3.99       A_1
2   3       38694   97.75   3.94       A_1
3   4       38694  117.50   3.92       A_1
4   5       38694  144.25   3.78       A_1

In [33]:
experiments.head()

,ID,SourceID,MatrixID,In_on,Ph,Aw,Temperature,LinkId,UserId
0,1,1,beef,ground beef salad with mayonnaise,5.5,NaN,30.0,O418_Ec,NaN
1,2,1,beef,ground beef salad with mayonnaise,5.7,NaN,21.0,O414_Ec,NaN
2,3,1,beef,ground beef salad with mayonnaise,5.7,NaN,30.0,O417_Ec,NaN
3,4,1,beef,ground beef salad with mayonnaise,5.9,NaN,21.0,O413_Ec,NaN
4,5,1,beef,ground beef salad with mayonnaise,5.9,NaN,30.0,O416_Ec,NaN

In [34]:
responses.head()

,ID,ExperimentID,Spec_rate,RateMethod,MethodID,OrganismID,OrganismSpecification,Comment,Logc0,LogcVar,TObs,Assumed
0,1,6,-0.009999,NaN,plate_count,ec,"Serotype(s): O157:H7, Strain(s): 301C 204P 505...",NaN,NaN,0.3,72.0,NaN
1,2,26,0.628000,NaN,plate_count,ec,"Serotype(s): O157:H7, Strain(s): 301C 204P 505...",NaN,NaN,4.5,24.0,NaN
2,3,22,0.431700,NaN,plate_count,ec,"Serotype(s): O157:H7, Strain(s): 301C 204P 505...",NaN,NaN,3.9,24.0,NaN
3,4,23,0.431700,NaN,plate_count,ec,"Serotype(s): O157:H7, Strain(s): 301C 204P 505...",NaN,NaN,3.4,24.0,NaN
4,5,12,0.328900,NaN,plate_count,ec,"Serotype(s): O157:H7, Strain(s): 301C 204P 505...",NaN,NaN,2.4,24.0,NaN